Repository GsTYPO3/core-patches, pull requests merged in 2022-04, with the labels that each got.

#41 [TASK] Introduce config classes
  .ddev/config.yaml
  .github/workflows/continuous-integration.yml
  .vscode/launch.json
  .vscode/settings.json
  composer.json
  rector.php
  src/Config.php
  src/Config/Changes.php
  src/Config/Changes/Change.php
  src/Config/ConfigAwareInterface.php
  src/Config/Packages.php
  src/Config/Patches.php
  src/Config/Patches/PackagePatches.php
  src/Config/PreferredInstall.php
  src/Plugin.php
  src/Utility/ComposerUtils.php
  tests/Unit/Config/Changes/ChangeTest.php
  tests/Unit/Config/ChangesTest.php
  tests/Unit/Config/PackagesTest.php
  tests/Unit/Config/Patches/PackagePatchesTest.php
  tests/Unit/Config/PatchesTest.php
  tests/Unit/Config/PreferredInstallTest.php
  tests/Unit/ConfigTest.php
  tests/Unit/TestCase.php
  tests/project/composer.json
Labels: bug, maintenance

#42 [TASK] Optimize release workflow
  .github/workflows/release.yml
Labels: maintenance

#44 [BUGFIX] Fix wrong type annotation in tests
  tests/Unit/Command/ApplyCommandTest.php
  tests/Unit/Command/RemoveCommandTest.php
  tests/Unit/Command/UpdateCommandTest.php
  tools/phpstan/composer.json
Labels: bug

#43 [TASK] Update gitattributes
  .gitattributes
Labels: maintenance

#45 [TASK] Move Rector to dedicated namespace
  tools/phpstan/composer.json
  tools/rector/composer.json
Labels: maintenance
