Repository GsTYPO3/core-patches, pull requests merged in 2023-05, with the labels that each got.

#58 [BUGFIX] Perform version comparison with branch name prefix only
  src/Utility/ComposerUtils.php
  tests/Unit/Fixtures/composer.patches.json
  tests/Unit/Utility/ComposerUtilsTest.php
Labels: bug

#62 [TASK] Update actions
  .github/workflows/continuous-integration.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
Labels: maintenance

#63 [TASK] Update badges
  README.md
Labels: maintenance

#64 [TASK] Refactor Config classes
  src/Config.php
  src/Config/Changes.php
  src/Config/Changes/Change.php
  src/Config/ConfigAwareInterface.php
  src/Config/Packages.php
  src/Config/Patches.php
  src/Config/Patches/PackagePatches.php
  src/Config/PreferredInstall.php
  src/Utility/ComposerUtils.php
  src/Utility/PatchUtils.php
  tests/Unit/Config/Changes/ChangeTest.php
  tests/Unit/Config/ChangesTest.php
  tests/Unit/Config/PackagesTest.php
  tests/Unit/Config/Patches/PackagePatchesTest.php
  tests/Unit/Config/PatchesTest.php
  tests/Unit/Config/PreferredInstallTest.php
  tests/Unit/ConfigTest.php
Labels: maintenance

#65 [TASK] Optimize Command tests
  src/Command/Typo3/Patch/ApplyCommand.php
  src/Command/Typo3/Patch/RemoveCommand.php
  src/Command/Typo3/Patch/UpdateCommand.php
  src/CommandProvider.php
  tests/Unit/Command/ApplyCommandTest.php
  tests/Unit/Command/RemoveCommandTest.php
  tests/Unit/Command/UpdateCommandTest.php
  tests/Unit/phpunit.xml
Labels: maintenance

#66 [TASK] Bump dev dependencies
  composer.json
Labels: maintenance

#68 [TASK] Implement more tests
  src/Gerrit/Entity/AbstractEntity.php
  src/Gerrit/RestApi.php
  tests/Unit/CommandProviderTest.php
  tests/Unit/Gerrit/Entity/AbstractEntityTest.php
  tests/Unit/Gerrit/Entity/ChangeInfoTest.php
  tests/Unit/Gerrit/Entity/IncludedInInfoTest.php
  tests/Unit/Gerrit/Entity/TestEntity.php
  tests/Unit/Gerrit/RestApiTest.php
Labels: maintenance

#67 [TASK] Make tests more strict
  .github/workflows/continuous-integration.yml
  src/Config/Changes.php
  src/Config/Patches.php
  src/Config/PreferredInstall.php
  src/Utility/ComposerUtils.php
  tests/Unit/Command/ApplyCommandTest.php
  tests/Unit/Command/RemoveCommandTest.php
  tests/Unit/Command/UpdateCommandTest.php
  tests/Unit/CommandProviderTest.php
  tests/Unit/Config/Changes/ChangeTest.php
  tests/Unit/Config/ChangesTest.php
  tests/Unit/Config/PackagesTest.php
  tests/Unit/Config/Patches/PackagePatchesTest.php
  tests/Unit/Config/PatchesTest.php
  tests/Unit/Config/PreferredInstallTest.php
  tests/Unit/ConfigTest.php
  tests/Unit/Gerrit/Entity/AbstractEntityTest.php
  tests/Unit/Gerrit/Entity/ChangeInfoTest.php
  tests/Unit/Gerrit/Entity/IncludedInInfoTest.php
  tests/Unit/Gerrit/RestApiTest.php
  tests/Unit/Utility/ComposerUtilsTest.php
  tests/Unit/phpunit.xml
Labels: maintenance

#69 [TASK] Add tests for PatchUtils
  .github/workflows/continuous-integration.yml
  src/Config.php
  src/Utility/ComposerUtils.php
  src/Utility/PatchUtils.php
  tests/Unit/Utility/PatchUtilsTest.php
Labels: maintenance

#55 [FEATURE] Check target branch
  README.md
  src/Config.php
  src/Gerrit/Entity/ChangeInfo.php
  src/Gerrit/RestApi.php
  src/Utility/ComposerUtils.php
  tests/Unit/ConfigTest.php
  tests/Unit/Fixtures/composer.json
  tests/Unit/Gerrit/Entity/ChangeInfoTest.php
  tests/Unit/Gerrit/RestApiTest.php
Labels: enhancement

#60 [FEATURE] Detect CI to avoid removal of outdated patches
  .github/workflows/continuous-integration.yml
  README.md
  src/Config.php
  src/Plugin.php
  src/Utility/ComposerUtils.php
  src/Utility/Utils.php
  tests/Unit/Command/ApplyCommandTest.php
  tests/Unit/Command/RemoveCommandTest.php
  tests/Unit/Command/UpdateCommandTest.php
  tests/Unit/ConfigTest.php
  tests/Unit/Utility/ComposerUtilsTest.php
  tests/Unit/Utility/UtilsTest.php
Labels: enhancement

#71 [DOCS] Update install instructions
  README.md
Labels: documentation

#72 [DOCS] Update toc and minor changes
  README.md
Labels: documentation

#73 [TASK] Update branch-alias
  composer.json
Labels: maintenance
